datasets:
  clean: /mnt/startiger0/nbogoych/enfr/dedup_fren/clean.gz # 2.4 GB
  cleanish: /mnt/startiger0/nbogoych/enfr/dedup_fren/clean.med.gz # 1.3 GB
  medium: /mnt/startiger0/nbogoych/enfr/dedup_fren/dirty.gz # 1.8 GB
  dirty: /mnt/startiger0/nbogoych/enfr/dedup_fren/medium.gz # 33 GB

stages:
  - start
  - mid
  - end

start:
  - clean 0.6
  - cleanish 0.2
  - medium 0.1
  - dirty 0
  - until clean 1 # Until two epochs of clean

mid:
  - clean 0.35
  - cleanish 0.15
  - medium 0.1
  - dirty 0.4
  - until dirty 1

end:
  - clean 0.4
  - cleanish 0.15
  - medium 0.15
  - dirty 0.3
  - until dirty inf

modifiers:
  - UpperCase: 0.05 # Apply uppercase randomly to 5% of sentences. See below
  - TitleCase: 0.05
  - Typos: 0.05
  - Tags: 0.1
    augment: 1
  - Noise: 0.01
    min_word_legnth: 2 # Minumum lenght of each fake word, defaults is 2 if left blank
    max_word_length: 5 # Maximum lenght of each fake word, defaults is 5 if left blank
    max_words: 4       # Maximu number of fake words, default is 4 if left blank

seed: 1111
