datasets:
  clean: /mnt/startiger0/nbogoych/enfr/dedup_fren/clean.gz # 2.4 GB
  cleanish: /mnt/startiger0/nbogoych/enfr/dedup_fren/clean.med.gz # 1.3 GB
  medium: /mnt/startiger0/nbogoych/enfr/dedup_fren/medium.gz # 1.8 GB
  dirty: /mnt/startiger0/nbogoych/enfr/dedup_fren/dirty.gz # 33 GB

stages:
  - start
  - mid
  - end

start:
  - clean 0.6
  - cleanish 0.2
  - medium 0.1
  - dirty 0
  - until clean 1 # Until two epochs of clean

mid:
  - clean 0.35
  - cleanish 0.15
  - medium 0.1
  - dirty 0.4
  - until dirty 1

end:
  - clean 0.4
  - cleanish 0.15
  - medium 0.15
  - dirty 0.3
  - until dirty inf

modifiers:
- UpperCase: 0.05 # Apply uppercase randomly to 5% of sentences. See below
- TitleCase: 0.05

seed: 1111
